# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setDocumentMode(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.files = QtWidgets.QListWidget(self.centralwidget)
        self.files.setMinimumSize(QtCore.QSize(782, 475))
        self.files.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.files.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.files.setAcceptDrops(True)
        self.files.setToolTipDuration(-1)
        self.files.setFrameShadow(QtWidgets.QFrame.Plain)
        self.files.setProperty("showDropIndicator", False)
        self.files.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.files.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.files.setIconSize(QtCore.QSize(115, 115))
        self.files.setMovement(QtWidgets.QListView.Free)
        self.files.setProperty("isWrapping", True)
        self.files.setGridSize(QtCore.QSize(120, 140))
        self.files.setViewMode(QtWidgets.QListView.IconMode)
        self.files.setItemAlignment(QtCore.Qt.AlignLeading)
        self.files.setObjectName("files")
        item = QtWidgets.QListWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/charizard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.files.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../images/shadow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.files.addItem(item)
        self.verticalLayout.addWidget(self.files)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.newFile = QtWidgets.QPushButton(self.frame)
        self.newFile.setMinimumSize(QtCore.QSize(0, 30))
        self.newFile.setObjectName("newFile")
        self.horizontalLayout.addWidget(self.newFile)
        self.edit = QtWidgets.QPushButton(self.frame)
        self.edit.setMinimumSize(QtCore.QSize(0, 30))
        self.edit.setObjectName("edit")
        self.horizontalLayout.addWidget(self.edit)
        self.rename = QtWidgets.QPushButton(self.frame)
        self.rename.setMinimumSize(QtCore.QSize(0, 30))
        self.rename.setObjectName("rename")
        self.horizontalLayout.addWidget(self.rename)
        self.deleteFile = QtWidgets.QPushButton(self.frame)
        self.deleteFile.setMinimumSize(QtCore.QSize(0, 30))
        self.deleteFile.setObjectName("deleteFile")
        self.horizontalLayout.addWidget(self.deleteFile)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuClose = QtWidgets.QMenu(self.menubar)
        self.menuClose.setObjectName("menuClose")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuClose.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.files.setSortingEnabled(False)
        __sortingEnabled = self.files.isSortingEnabled()
        self.files.setSortingEnabled(False)
        item = self.files.item(0)
        item.setText(_translate("MainWindow", "Dark.txt"))
        item = self.files.item(1)
        item.setText(_translate("MainWindow", "Shadow.txt"))
        self.files.setSortingEnabled(__sortingEnabled)
        self.newFile.setText(_translate("MainWindow", "New"))
        self.edit.setText(_translate("MainWindow", "Edit"))
        self.rename.setText(_translate("MainWindow", "Rename"))
        self.deleteFile.setText(_translate("MainWindow", "Delete"))
        self.menuClose.setTitle(_translate("MainWindow", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
